language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- PACKAGE_VERSION="1.0" UNITY_DOWNLOAD_CACHE="$(pwd)/unity_download_cache"

cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release/*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true   
    
    
before_install:
- rvm get stable
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh

after_success:
- ./travis-build/export-unity-package.sh

before_deploy:
- git config --local user.name "$GITHUB_USERNAME"
- git config --local user.email "$GITHUB_EMAIL"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
